version: '3.8'

services:
  database:
    image: mysql:8
    container_name: sgu-database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: adj-demo
    ports:
      - "3307:3306"
    volumes:
      - sgu-volume:/var/lib/mysql
    networks:
      - sgu-net
    restart: unless-stopped

  backend:
    build:
      context: ./server
    image: server:1.0-sgu
    container_name: sgu-backend
    environment:
      SERVER_PORT: 8081
      DB_HOST: database
      DB_PORT: 3306
      DB_NAME: adj-demo
      DB_USER: root
      DB_PASS: root
    ports:
      - "8081:8080"
    depends_on:
      - database
    networks:
      - sgu-net
    restart: unless-stopped

  frontend:
    build:
      context: ./client
      args:
        API_HOST: backend
        API_PORT: 8080
        API_BASE: /api-users
    image: client:1.0-sgu
    container_name: sgu-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - sgu-net
    restart: unless-stopped

volumes:
  sgu-volume:
    external: true

networks:
  sgu-net:
    external: true
